name = "Oceanostics"
uuid = "d0ccf422-c8fb-49b5-a76d-74acdde946ac"
authors = ["tomchor <tomaschor@gmail.com>"]
version = "0.6.3"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Oceananigans = "^0.68"
julia = "^1.6"

[targets]
test = ["Test"]

